### ISSUE TITLE
Update example and tutorial links in blog posts

### ISSUE THREAD

**Issue by kevinrobinson** [tensorflow/fairness-indicators#197]
hello! 👋 

In looking at some blog posts that are ranked highly when typing "fairness indicators" in search engines ([Google AI blog](https://ai.googleblog.com/2019/12/fairness-indicators-scalable.html), [TF blog](https://blog.tensorflow.org/2019/12/fairness-indicators-fair-ML-systems.html)), I found that many of the links are broken.

### In the blog posts:
<img width="637" alt="Screen Shot 2020-12-08 at 9 53 28 AM" src="https://user-images.githubusercontent.com/1056957/101499576-6c6f0180-393b-11eb-9387-f77e9f176f51.png">
<img width="659" alt="Screen Shot 2020-12-08 at 9 53 32 AM" src="https://user-images.githubusercontent.com/1056957/101499573-6bd66b00-393b-11eb-89f1-074a4d68ced0.png">

I submitted a fix for this in the REAMDE in This is the same problem as https://github.com/tensorflow/fairness-indicators/pull/196, but since the blog posts from December 2019 come up so highly in search engines, it might be good to backport the link fixes and republish those posts too.  Thanks! 👍

**Comment by shuklak13** [comment]
Looks like this has been resolved.
