### ISSUE TITLE
Image in Fairness_Indicators_Lineage_Case_Study.ipynb is not publicly accessible

### ISSUE THREAD

**Issue by BioGeek** [tensorflow/fairness-indicators#261]
## URL with the issue:

https://github.com/tensorflow/fairness-indicators/blob/master/g3doc/tutorials/Fairness_Indicators_Lineage_Case_Study.ipynb

## Description of issue (what needs changing):

The link to the image on line 899 in the notebook is not publicly accessible, you need to sign in with a Google account to view it.

```
        "![Type I and Type II errors](http://services.google.com/fh/gumdrop/preview/blogs/type_i_type_ii.png)\n",
```

### Correct links

Link to a publicly accessible `type_i_type_ii.png`.

**Comment by JeremyHurwitz** [comment]
Thanks for the report! It looks like that colab no longer exists, so closing this as obsolete.
