### ISSUE TITLE
Widget Not Working in Jupyter Notebook Environment

### ISSUE THREAD

**Issue by zoraxl** [tensorflow/fairness-indicators#51]
Hi Dev team,

I am studying the fairness indicator when trying to use it locally instead of colab. When I am trying to render the widget from the following example, the results are not showing up:

event_handlers={'slice-selected':
                wit.create_selection_callback(wit_data, DEFAULT_MAX_EXAMPLES)}
widget_view.render_fairness_indicator(eval_result=eval_result,
                                      slicing_column=slice_selection,
                                      event_handlers=event_handlers
                                      )
Later I checked the source code and find out when the environment is not colab, it will pass to a empty class called FairnessIndicatorViewer. I wonder is it intended or it will be fixed later? Many thanks!

**Comment by shuklak13** [comment]
Hi - sorry you're running into an error. I ran the latest version of the fairness indicator widget in jupyter on my local environment and was able to render it successfully.

The [FairnessIndicatorViewer](https://github.com/tensorflow/model-analysis/blob/master/tensorflow_model_analysis/addons/fairness/notebook/jupyter/widget.py#L23) class should not be empty. Perhaps you're using an outdated or incomplete installation. Could you share a link or screenshot of your source code?

**Comment by shuklak13** [comment]
To make sure your installation is up to date, please run the following:

    pip install tensorflow
    pip install tensorflow_data_validation
    pip install tensorflow-model-analysis
    pip install jupyter

    jupyter nbextension enable --py widgetsnbextension --sys-prefix
    jupyter nbextension install --py --symlink tensorflow_model_analysis --sys-prefix
    jupyter nbextension enable --py tensorflow_model_analysis --sys-prefix

**Comment by drcat101** [comment]
Hi Zora, I'm not on the dev team but I have some experience using this tool. I'm not sure where your code example is from, but I have found that accessing Fairness Indicators via TensorBoard works well in a non-Colab environment. You can follow these steps:
https://github.com/tensorflow/tensorboard/blob/master/docs/fairness-indicators.md#usage

**Comment by zoraxl** [comment]
Hey Shuklak!

Thanks for the feedback. I have tried changing the jupyter widget extension command into the following and it works. It turns out to be the problem of permission. 

jupyter nbextension enable --py widgetsnbextension
jupyter nbextension install --py --user tensorflow_model_analysis
jupyter nbextension enable --py tensorflow_model_analysis --user

**Comment by bricha2** [comment]
Hi, I had same problem. I was able to enable the widgetsnbextension, but the install/enabling of tensorflow_model_analysis led to Error message: 

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named tensorflow_model_analysis
